-- 코드를 입력하세요
# SELECT USER_ID, PRODUCT_ID
# from ONLINE_SALE
# group BY USER_ID, PRODUCT_ID
# having count(*)>1
# ORDER BY USER_ID, PRODUCT_ID DESC;

SELECT USER_ID, PRODUCT_ID
FROM ONLINE_SALE
GROUP BY USER_ID, PRODUCT_ID
HAVING COUNT(*) > 1
ORDER BY USER_ID ASC, PRODUCT_ID DESC;