SELECT YEAR(s.SALES_DATE) AS "YEAR",MONTH(s.SALES_DATE) AS "MONTH",i.GENDER AS "GENDER",COUNT(DISTINCT s.USER_ID) AS "USERS"
FROM ONLINE_SALE s
JOIN USER_INFO i
ON s.USER_ID = i.USER_ID
WHERE i.GENDER IS NOT NULL
GROUP BY 
    YEAR(s.SALES_DATE), 
    MONTH(s.SALES_DATE), 
    i.GENDER
ORDER BY `YEAR`, `MONTH`, `GENDER`;
