SELECT
TREE.ITEM_ID,
INFO.ITEM_NAME,
INFO.RARITY
FROM ITEM_TREE AS TREE
LEFT JOIN ITEM_INFO AS INFO
ON TREE.ITEM_ID = INFO.ITEM_ID
WHERE TREE.PARENT_ITEM_ID IN (
SELECT
ITEM_ID
FROM ITEM_INFO
WHERE RARITY = 'RARE'
)
ORDER BY
TREE.ITEM_ID DESC;